# Generated by Django 2.2.11 on 2020-05-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazdy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frc',
            name='instytucja',
            field=models.CharField(default='Politechnika Poznańska, IMRiPS', max_length=40, null=True),
        ),
    ]
