# Generated by Django 2.2.11 on 2020-05-20 14:30

import Pojazdy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazdy', '0002_auto_20200517_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdymodel',
            name='VIN',
            field=models.CharField(max_length=17, unique=True, validators=[Pojazdy.models.VIN_walidator, Pojazdy.models.VIN_unique]),
        ),
        migrations.AlterField(
            model_name='pojazdymodel',
            name='nr_rej',
            field=models.CharField(max_length=8, unique=True, validators=[Pojazdy.models.REJ_walidator, Pojazdy.models.REJ_unique], verbose_name='nr rej.'),
        ),
    ]
