# Generated by Django 2.2.11 on 2020-05-20 15:05

import Pojazdy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pojazdy', '0003_auto_20200520_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdymodel',
            name='VIN',
            field=models.CharField(max_length=17, unique=True, validators=[Pojazdy.models.VIN_walidator]),
        ),
    ]
