# Generated by Django 2.2.11 on 2020-05-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kierowcy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADRdriver',
            fields=[
                ('kierowca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Kierowcy.Kierowcy')),
                ('data_waznosci', models.DateField()),
                ('kat1', models.BooleanField(default=False)),
                ('kat7', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kwalifikacja',
            fields=[
                ('kierowca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Kierowcy.Kierowcy')),
                ('data_waznosci', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrawoJazdy',
            fields=[
                ('kierowca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Kierowcy.Kierowcy')),
                ('data_waznosci', models.DateField()),
                ('B', models.BooleanField(default=True)),
                ('CE', models.BooleanField(default=True)),
                ('BE', models.BooleanField(default=False)),
                ('C1', models.BooleanField(default=False)),
                ('C', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='kierowcy',
            name='PESEL',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
