# Generated by Django 2.2.11 on 2020-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kierowcy', '0002_auto_20200517_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kierowcy',
            name='PESEL',
            field=models.PositiveIntegerField(max_length=11, unique=True),
        ),
    ]
