# Generated by Django 2.2.11 on 2020-05-17 18:55

import Kierowcy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kierowcy', '0003_auto_20200517_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kierowcy',
            name='PESEL',
            field=models.CharField(max_length=11, unique=True, validators=[Kierowcy.models.PESEL_walidator]),
        ),
    ]
