# Generated by Django 2.2.11 on 2020-05-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kierowcy', '0004_auto_20200517_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrdriver',
            name='kierowca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='adr', serialize=False, to='Kierowcy.Kierowcy'),
        ),
        migrations.AlterField(
            model_name='kwalifikacja',
            name='kierowca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kwalifikacja', serialize=False, to='Kierowcy.Kierowcy'),
        ),
        migrations.AlterField(
            model_name='prawojazdy',
            name='kierowca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prawojazdy', serialize=False, to='Kierowcy.Kierowcy'),
        ),
    ]
