# Generated by Django 2.2.11 on 2020-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kierowcy', '0005_auto_20200517_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prawojazdy',
            name='C',
            field=models.BooleanField(default=True),
        ),
    ]
